services:
  backend:
    container_name: nooke-django
    build: ./api
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/api/
    ports:
      - 8002:8000
    env_file:
      - ./prod.env
    restart: unless-stopped