services:
  backend:
    container_name: nooke-django
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/api/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: unless-stopped