services:
  backend:
    container_name: nooke-django
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/api/
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: nooke-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=sampledb

volumes:
  postgres_data: